### PR TITLE
All scripts work now!

### PR DESCRIPTION
**Pull request by rudra-code-creator**
I have described an issue that is at the start of every command of every script in the repo and have fixed it.
if you want to know the issue I fixed in all the scripts read the oldest commit in this pull request for more info.

### CODE REVIEW

**Comment by JBNCK** [comment]
Thanks for contributing, but I see two problems with your pull request, so I can't directly merge it for now.
1. The mac and linux scripts are **not** the same. Mac and Linux use 2 different kernels (linux is a kernel) which mean that they need 2 different binaries. Thats why the mac script links to adb_mac/adb and the linux script to adb_lin/adb
2. As described in my adb reply, errors like "Package not installed for 0" are normal, thats why I included the warning. If you are only getting permission denied errors, you probably have to make the script and the adb binary executable.

**Comment by JBNCK** [comment]
I took over your idea of mentioning the deleted apps in the readme

**Comment by entrepernuer** [comment]
Hello again JBNCK.
I understand that Mac and Linux are not the same due to their different kernels but there both still UNIX based operating systems which means they both have Bash and other GNU core utilities and libraries installed on them therefore since they both have bash there both compatible with bash shell scripts (.sh) so we do not need to maintain two different scripts if you go and view the scripts you will see that they are both exactly the same. Any UNIX based system even if not Mac or Linux can run this script perfectly that is the beauty of UNIX. Both the files are exactly the same

**Comment by entrepernuer** [comment]
As described in my ADB reply, errors like "Package not installed for 0" is normal, that's why I included the warning. If you are only getting permission denied errors, you probably have to make the script and the ADB binary executable.

No, I am not getting permission denied errors I ran chmod +rwx

and yes it is true Package not installed for 0 is a normal error it just means the user must have forcibly removed the package sometime prior to running the script but other errors such as a runtime error aren't normal so I think a better way to praise it is Package not installed for 0 error is normal but other errors are not.

**Pull request closed without merging**
